import About from './About';
import Balance from './Balance';
import Filter from './filter';
import Header from './Header';
import Menu from './Menu';
import Profile from './Profile';
import Tours from './Tours';
import Tickets from './Ticket';
import PrivateRoutes from './privateRoutes';
import Loader from './loader';
export {About, Balance, Filter, Header, Menu, Profile , Tours, Loader, Tickets , PrivateRoutes};